# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
#  https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux 
files:
  - source: .
    destination: /home/ec2-user/apache-tomcat-8.5.82/webapps
  - source:
    destination:
permissions:
  - object:
    pattern:
    except:
    owner:
    group:
    mode: 
    acls:
      -
    context:
      user:
      type:
      range:
    type:
hooks:
 ApplicationStop:
    - location: /home/ec2-user/apache-tomcat-8.5.82/bin/shutdown.sh
      timeout: 20
      runas: ec2-user
 ApplicationStart:
    - location: /home/ec2-user/apache-tomcat-8.5.82/bin/startup.sh
      timeout: 20
      runas: ec2-user
